# Generated by Django 2.1.5 on 2021-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SABOR', 'SABOR DE PIZZA'), ('BEBIDA', 'BEBIDA'), ('COMBO', 'COMBO')], default='SABOR', max_length=6),
        ),
    ]
