# Generated by Django 2.1.5 on 2021-11-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='atualizado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criado',
        ),
    ]
