# Generated by Django 2.1.5 on 2021-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20211105_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=50, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('SABOR', 'SABOR DE PIZZA'), ('BEBIDA', 'BEBIDA'), ('COMBO', 'COMBO')], default='SABOR', max_length=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='urlImagem',
            field=models.URLField(blank=True),
        ),
    ]
