# Generated by Django 2.1.5 on 2021-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_taxa_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
